spring.application.name=VIKOBA

spring.datasource.url=jdbc:postgresql://localhost:5432/vikoba
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
# JWT Configuration
jwt.secret=VIKOBA_SECRET_KEY_2026_MNasta_SECURE_KEY_123456789
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG